version: '3'

################################################################################
# Ultra Image Server
# A production grade image processing server setup powered by imgproxy and nginx
#
# Author: Mai Nhut Tan <shin@shin.company>
# Copyright: 2021-2023 SHIN Company https://code.shin.company/
# URL: https://shinsenter.github.io/docker-imgproxy/
################################################################################

networks:
################################################################################
  default:
    driver: bridge


services:
  nginx:
    restart: always
    image: nginx
    container_name: imgproxy_nginx
    security_opt:
      - no-new-privileges:true
    volumes:
      - type: tmpfs
        target: /var/cache/nginx/imgproxy
        tmpfs:
          size: "1073741824"

      - type: bind
        source: ./nginx_logs
        target: /var/log/nginx

      - type: bind
        source: ./nginx_imgproxy.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    links:
      - imgproxy:imgproxy
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  imgproxy:
    restart: always
    image: darthsim/imgproxy:${IMGPROXY_TAG:-latest}
    container_name: imgproxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./:/opt/imgproxy:cached
      - /var/www/public:/mnt/media:ro
    #ports:
    #  - 8000:8080
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    environment:
      ### See:
      ### https://docs.imgproxy.net/configuration/options

      ### log and debug
      IMGPROXY_LOG_LEVEL: "info"
      IMGPROXY_ENABLE_DEBUG_HEADERS: "false"
      IMGPROXY_DEVELOPMENT_ERRORS_MODE: "false"
      IMGPROXY_REPORT_DOWNLOADING_ERRORS: "false"

      ### timeouts
      IMGPROXY_READ_TIMEOUT: 10
      IMGPROXY_WRITE_TIMEOUT: 10
      IMGPROXY_DOWNLOAD_TIMEOUT: 10
      IMGPROXY_KEEP_ALIVE_TIMEOUT: 300
      IMGPROXY_MAX_SRC_FILE_SIZE: 33554432 # 32MB
      IMGPROXY_MAX_SRC_RESOLUTION: 48

      ### image source
      IMGPROXY_TTL: 2592000 # client-side cache time is 30 days
      IMGPROXY_USE_ETAG: "false"
      IMGPROXY_SO_REUSEPORT: "true"
      IMGPROXY_IGNORE_SSL_VERIFICATION: "true"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /mnt/media
      IMGPROXY_SKIP_PROCESSING_FORMATS: "svg,webp,avif"

      ### presets
      IMGPROXY_AUTO_ROTATE: "true"
      IMGPROXY_FALLBACK_IMAGE_PATH: /opt/imgproxy/no-image-600x450.png
      IMGPROXY_PRESETS: default=resizing_type:auto/gravity:ce,logo=watermark:0.5:soea:10:10:0.15,center_logo=watermark:0.3:ce:0:0:0.3

      ### compression
      IMGPROXY_STRIP_METADATA: "true"
      IMGPROXY_STRIP_COLOR_PROFILE: "true"
      IMGPROXY_FORMAT_QUALITY: jpeg=81,webp=75,avif=81
      IMGPROXY_JPEG_PROGRESSIVE: "true"
      IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      IMGPROXY_ENFORCE_WEBP: "true"
      IMGPROXY_PNG_INTERLACED: "false"
      IMGPROXY_PNG_QUANTIZATION_COLORS: 128
      IMGPROXY_PNG_QUANTIZE: "false"
      IMGPROXY_MAX_ANIMATION_FRAMES: 64
      IMGPROXY_GZIP_COMPRESSION: 0
      IMGPROXY_AVIF_SPEED: 8
      IMGPROXY_ENABLE_CLIENT_HINTS: "true"
      IMGPROXY_ENFORCE_AVIF: "false"

      ### For URL signature
      # IMGPROXY_KEY: "<your key>"
      # IMGPROXY_SALT: "<your salt>"
      # IMGPROXY_SIGNATURE_SIZE: 32

      ### External source (S3)
      ### See: https://docs.imgproxy.net/image_sources/amazon_s3
      # IMGPROXY_USE_S3: "true"
      # IMGPROXY_S3_REGION: "us-west-1"
      # IMGPROXY_S3_ENDPOINT: "<your endpoint>"
      # AWS_ACCESS_KEY_ID: "<your id>"
      # AWS_SECRET_ACCESS_KEY: "<your key>"

      ### External source (Google Cloud)
      ### See: https://docs.imgproxy.net/image_sources/google_cloud_storage
      # IMGPROXY_USE_GCS: "true"
      # IMGPROXY_GCS_KEY: "<your key>"

      ### External source (Azure Blob)
      ### See: https://docs.imgproxy.net/image_sources/azure_blob_storage
      # IMGPROXY_USE_ABS: "true"
      # IMGPROXY_ABS_NAME: "<your name>"
      # IMGPROXY_ABS_KEY: "<your key>"
      # IMGPROXY_ABS_ENDPOINT: "<your endpoint>"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
